### PR TITLE
README: Add KRF

### PR DESCRIPTION
**Pull request by woodruffw**
Additionally, clean up some trailing whitespace.

### CODE REVIEW

**Comment by milabs** [comment]
KRF seems quite interesting project for me but it's not rootkit so I see no value of having it in the list. Don't you think so?

**Comment by woodruffw** [comment]
I'd argue that it's a rootkit, if not an offensive one:

1. It runs as a LKM
2. It rewrites the system call table, and is a useful resource for doing so safely/idiomatically
3. It allows users to inject faults in places that would almost never have them

Ultimately though, it's your repo. If you think that it doesn't meet your requirements, please feel free to pass on it 🙂

**Comment by milabs** [comment]
Thank you for keeping this repo alive!

**Comment by woodruffw** [comment]
No problem! Thanks for the merge!

**Pull request merged**
